//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace monitor.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estacion
    {
        public int EstacionId { get; set; }
        public string Nombre { get; set; }
        public string Monitor { get; set; }
        public string IPPLC { get; set; }
        public Nullable<byte> Soldador { get; set; }
        public string IPSoldador { get; set; }
        public Nullable<int> Estatus { get; set; }
        public Nullable<System.DateTime> FechaHora { get; set; }
    }
}
