//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace monitor.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Modelo
    {
        public string ModeloId { get; set; }
        public string NumeroModelo { get; set; }
        public Nullable<double> Routing { get; set; }
        public string RutaAyudaVisual { get; set; }
        public Nullable<byte> Estatus { get; set; }
        public Nullable<System.DateTime> FechaHora { get; set; }
    }
}
