//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace monitor.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MonitoreoEntities : DbContext
    {
        public MonitoreoEntities()
            : base("name=MonitoreoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Estacion> Estacion { get; set; }
        public virtual DbSet<Modelo> Modelo { get; set; }
        public virtual DbSet<Pieza> Pieza { get; set; }
        public virtual DbSet<PiezasTomadas> PiezasTomadas { get; set; }
        public virtual DbSet<ResultadoSoldadora> ResultadoSoldadora { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    }
}
