//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace monitor.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pieza
    {
        public int PiezaId { get; set; }
        public string ModeloId { get; set; }
        public Nullable<int> Operadores { get; set; }
        public Nullable<int> Estacion { get; set; }
        public Nullable<int> Estado { get; set; }
        public Nullable<System.DateTime> FechaHora { get; set; }
    }
}
