//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace monitor.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        public int NumeroEmpleado { get; set; }
        public Nullable<int> TipoEmpleado { get; set; }
        public byte[] HuellaDigita { get; set; }
        public Nullable<byte> Activo { get; set; }
        public Nullable<int> Estatus { get; set; }
        public Nullable<System.DateTime> FechaHora { get; set; }
    }
}
